### PR TITLE
 Update Pylint to 2.13.8  and pylint-django to 2.5.3

### PR DESCRIPTION
**Pull request by ukanga**
There is also a new result with the `pylint-django` update hence a test was updated.

 > Result(E0102.py,Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured,E5110,1),

### CODE REVIEW

**Comment by lolgab** [comment]
Thank you for this contribution @ukanga.
We have a [Scala documentation generator](https://github.com/codacy/codacy-pylint-python3/blob/master/doc-generator/src/main/scala/codacy/pylint/Main.scala) in the repository which is now failing because the website link is either wrong or it changed too much with the new version

**Comment by ukanga** [comment]
@lolgab Thanks for the review.

The table form changed to description ist in the Pylint documentation. I hope it is okay I removed all files and regenerated the files, some were no longer being generated which seem to be discontinued rules in Pylint.

I am not sure about the change to `run_multiple_tests: false` - not enough information as to why it failed and if it has to be true.

**Comment by lolgab** [comment]
I enabled `run_multiple_tests` again. It is an internal integration testing framework for Codacy tools. You can read more here: https://github.com/codacy/codacy-plugins-test#multiple-test-definition
Probably the change broke some tests. Let's see what does fail when the CI finishes.

**Comment by ukanga** [comment]
@lolgab I have resolved the failing tests.

**Pull request closed without merging**
